version: '3' # docker compose 버전
services:
    mysql57:
        image: mysql:5.7.22
        container_name: mysql57 # 컨테이너 이름
        restart: unless-stopped
        tty: true
        ports:
            - 43060:3306 # 로컬의 43306 포트를 컨테이너의 3306포트로 연결
        environment:
            MYSQL_DATABASE: community
            MYSQL_USER: cuser
            MYSQL_PASSWORD: cpassword123
            MYSQL_ROOT_PASSWORD: cpassword123
            TZ: Asia/Seoul
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d
